# Generated by Django 4.1 on 2022-09-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_course_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='viewers',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
