# Generated by Django 4.1 on 2022-09-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pov',
            field=models.CharField(max_length=500, null=True, verbose_name='Point of view'),
        ),
    ]
