# Generated by Django 4.1 on 2022-09-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_likers_comment_likes_alter_comment_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='sender',
        ),
    ]
