# Generated by Django 4.1 on 2022-09-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comment_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likers',
        ),
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
