# Generated by Django 4.1 on 2022-09-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
