# Generated by Django 4.1 on 2022-09-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_comment_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='file',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default='$0', max_length=100),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='uploaded')),
                ('demo', models.BooleanField()),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.course')),
                ('head_line', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.headline')),
            ],
        ),
    ]
