# Generated by Django 4.1 on 2022-09-22 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0025_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='buy_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
