# Generated by Django 4.1 on 2022-09-22 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_remove_buy_user_buy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='user',
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
