# Generated by Django 4.1 on 2022-09-22 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0027_remove_buy_user_buy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='buyer',
            field=models.ManyToManyField(blank=True, default=None, related_name='buyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
