# Generated by Django 4.1 on 2022-10-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='Course',
            new_name='course',
        ),
    ]
